% Extract static Rsc data for all SEF/FEF-SC pairs
% see also CREATESATSEFRSCDB

oFilename = 'dataProcessed/satSefPaper/analysis/spkCorr/summary/SAT_SEF_StaticRscAllPairs.mat';
areaPairs = {
    'SEF-FEF'    
    'SEF-SC'     
    'FEF-SC'     
    'SEF-SEF' 
    'FEF-FEF'    
    'SC-SC'      
    };
corrMatDirs = strcat('dataProcessed/satSefPaper/analysis/spkCorr/spkCorr_',areaPairs,'/mat');
corrDatFields = {
    % cellPairInfo fields to extract
    'Pair_UID'        
    'X_monkey'        
    'X_sessNum'       
    'X_sess'          
    'X_unitNum'       
    'Y_unitNum'       
    'X_unit'          
    'Y_unit'          
    'X_area'          
    'Y_area'          
    'X_visGrade'      
    'Y_visGrade'      
    'X_visField'      
    'Y_visField'      
    'X_visType'       
    'Y_visType'       
    'X_moveGrade'     
    'Y_moveGrade'     
    'X_moveField'     
    'Y_moveField'     
    'X_errGrade'      
    'Y_errGrade' 
    'X_isErrGrade'      
    'Y_isErrGrade' 
    'X_errField'      
    'Y_errField'      
    'X_rewGrade'      
    'Y_rewGrade'      
    'X_isRewGrade'      
    'Y_isRewGrade'      
    'X_taskType'      
    'X_Hemi'          
    'Y_Hemi'          
    'X_Grid'          
    'Y_Grid'          
    'X_GridAP_ML'     
    'Y_GridAP_ML'     
    'X_Depth'         
    'Y_Depth'         
    'X_Depth0'        
    'Y_Depth0'        
    'X_newDepth'      
    'Y_newDepth'      
    'XY_Dist'         
    'isOnSameChannel' 
    % spkCorr fields to extract
    'condition'          
    'alignedName'        
    'alignedEvent'       
    'alignedTimeWin'     
    'trialNosByCondition'
    'xBaselineMeanStd' 
    'yBaselineMeanStd' 
    'critRho10'          
    'critRho05'          
    'critRho01'                  
    'rho_pval_win_50ms'     
    'rho_pval_static_50ms'    
    'rho_pval_static_Z_baseline_50ms'  
    'rho_pval_static_Z_trial_50ms' 
    'rho_pval_win_150ms'     
    'rho_pval_static_150ms'    
    'rho_pval_static_Z_baseline_150ms'  
    'rho_pval_static_Z_trial_150ms' 
    'rho_pval_win_200ms'     
    'rho_pval_static_200ms'    
    'rho_pval_static_Z_baseline_200ms'  
    'rho_pval_static_Z_trial_200ms' 
    'xWaves'
    'yWaves'
    'xWaveWidths'
    'yWaveWidths'
    };
